name = "BIGBOSS_MODULE"
description = "Keep track of spawntimers for world bosses"
github = "Nadybot/BIGBOSS_MODULE"
version = "1.0.4"
author = "Nadyita"
bot_type = "Nadybot"
bot_version = ">=5.2.0, <5.3.0"
